#!/bin/bash

# Image details
DOCKERHUB_USER=platinumcd
IMAGE=analog-llvm-riscv-musl
RELEASE=1.0.0

# Mounting
MOUNT_DIR=/local
BUILD_DEST=/opt

# Compiler variables
COMPILER=$BUILD_DEST/llvm/bin/clang++
TARGET=riscv64-unknown-linux-musl
TOOLCHAIN=$BUILD_DEST/riscv
SYSROOT=$BUILD_DEST/riscv/sysroot

# Define the full command using the variables
CC="$COMPILER --target=$TARGET --gcc-toolchain=$TOOLCHAIN --sysroot=$SYSROOT"

# CXX_FLAGS="-fopenmp" # For `./cpp_compiler tests/openmp_example.cpp`
CXX_FLAGS=""

docker run --rm \
    -v $(pwd):$MOUNT_DIR               \
    $DOCKERHUB_USER/$IMAGE:$RELEASE    \
    $CC $CXX_FLAGS $MOUNT_DIR/$1 -o $MOUNT_DIR/"${1%.cpp}_cpp.out"
