#!/bin/bash
EXE=$1
JSON=sst_env/cross_sim_params.json
VERBOSE=0

DOCKERHUB_USER=platinumcd
SST_IMAGE=analog-sst-crosssim
RELEASE=1.0.0

docker run -it \
    -v $(pwd):/local \
    -e VANADIS_EXE=/local/$EXE \
    -e CROSS_SIM_JSON=/local/$JSON \
    -e VANADIS_VERBOSE=$VERBOSE \
    $DOCKERHUB_USER/$SST_IMAGE:$RELEASE sh -c "cd /local/sst_env && sst mvm_rocc_vanadis.py"
